services:
  - type: web
    name: queen-stone-gallery
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: ADMIN_USERNAME
        value: Admin
      - key: ADMIN_PASSWORD
        value: 8888
      - key: ADMIN_PIN
        value: 1234
